### ISSUE TITLE
Building error in new empty project

### ISSUE THREAD

**Issue by san-smith** [FyroxEngine/Fyrox#472] opened 2023-07-22 06:48 UTC
Hi.
I create a new empty project:
```bash
fyrox-template init --name my_game --style 3d
```
Then I run 
```bash
cargo run --package editor --release
```
And I've got the error:
```bash
[ERROR]: Failed to load settings, fallback to default. Reason: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(SpannedError { code: ExpectedStructLike, position: Position { line: 40, col: 27 } })', /home/san-smith/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fyrox-0.30.0/src/material/shader/mod.rs:634:69
```

**Comment by mrDIMAS** [comment] 2023-07-22 07:08
Hi, this error comes from `nalgebra`'s breaking changes, that were published as patch. To fix this, you need to update to latest version of the engine - https://fyrox-book.github.io/fyrox/beginning/scripting.html#using-the-latest-engine-version

**Comment by san-smith** [comment] 2023-07-22 07:16
It works, thanks!

**Comment by mrDIMAS** [comment] 2023-07-22 17:19
0.31 is now released and the issue is fixed there. Closing this one.

**Closed by mrDIMAS** 2023-07-22 17:19 UTC

**Comment by ktimam** [comment] 2023-08-24 07:52
Receiving same error.
Running fyrox-template upgrade --version nightly command in game's directory doesn't fix the problem.

**Comment by mrDIMAS** [comment] 2023-08-24 10:37
@ktimam  I re-checked this on latest version of the engine and it does not reproduce. What's the dependencies versions in your `Cargo.toml`s?

**Comment by ktimam** [comment] 2023-08-24 10:41
[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
my_game = { path = "../game" }

[dependencies.fyrox ]
git = "https://github.com/FyroxEngine/Fyrox"

[dependencies.fyroxed_base ]
git = "https://github.com/FyroxEngine/Fyrox"

**Comment by ktimam** [comment] 2023-08-31 08:04
Tried downloading the latest code and running "cargo run --example 2d_scene --release"
Still gives the same error.
