### ISSUE TITLE
[editor bug] Fonts blurry with display scaling 200% in GNOME using X11

### ISSUE THREAD

**Issue by fnune** [FyroxEngine/Fyrox#501] opened 2023-08-12 14:20 UTC
The fonts in the editor look blurry. Note that it's only the fonts: other graphics such as the scene preview and icons scale up properly.

![image](https://github.com/FyroxEngine/Fyrox/assets/16181067/bd2ed9bf-af5f-407f-be61-663a8dcceb70)

Here's a close-up:

![image](https://github.com/FyroxEngine/Fyrox/assets/16181067/2a3679a2-ce30-431a-bb76-858572d5e053)

And here's a comparison with another window with correct scaling:

![image](https://github.com/FyroxEngine/Fyrox/assets/16181067/7974d616-b416-4fce-9b41-e7b23a55bc07)

Some information about my system:

```
 ~/Development/fyrox/game => uname -a
Linux feanor 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux

 ~/Development/fyrox/game => gnome-shell --version
GNOME Shell 43.6

 ~/Development/fyrox/game => echo $XDG_SESSION_TYPE
x11
```

**Comment by mrDIMAS** [comment] 2023-08-13 07:18
Hi, this is because Fyrox uses bitmap fonts and bakes font atlas in 1:1 ratio.

**Comment by fnune** [comment] 2023-08-13 11:24
I see. Do you think it's feasible to change that?

If I were to take a look at it myself, where should I start?

**Comment by mrDIMAS** [comment] 2023-08-13 20:51
Hard to tell, the problem is quite complex. At first, when display scaling is applied to the UI, it just scales the geometry of the text (each quad per glyph). This means that the UI does not care what is actually placed on these text quads, it just generates geometry of a proper size. The renderer then using a font atlas to render glyphs. This is where the problem hides - font atlas was generated to 100% display scaling, but used with 200%. So you can begin at https://github.com/FyroxEngine/Fyrox/blob/master/fyrox-ui/src/ttf.rs and try to play with the font atlas bitmap size.

**Comment by perry-blueberry** [comment] 2023-10-01 19:15
This seems to be an issue on 100% scaling X11 as well.
![image](https://github.com/FyroxEngine/Fyrox/assets/16760830/f891c27f-f499-4a68-ab1b-1489dbfb592e)

**Comment by DanielJoyce** [comment] 2024-03-14 16:34
Hmm, so no support for Signed Distance Field fonts?

**Comment by mrDIMAS** [comment] 2024-03-14 17:31
This issue should be partially fixed by layout rounding feature, that was added recently.

**Comment by mrDIMAS** [comment] 2024-12-19 08:47
Blurry fonts are fixed now. Here are two images for comparison (it is better to open both images in full screen on separate tabs and switch between them so see the difference better).

**Without** the fix (blurry):

![200%-no-fix](https://github.com/user-attachments/assets/54f52645-ed8c-4c18-8384-388b209a3a23)

**With** fix:
![200%-with-fix](https://github.com/user-attachments/assets/57c09cf1-78fe-423d-8422-048eae79b1b4)

**Closed** 2024-12-19 08:48 UTC
