### ISSUE TITLE
Editor extremely slow, making it completely unusable on my system

### ISSUE THREAD

**Issue by christofferaakre** [FyroxEngine/Fyrox#436] opened 2023-03-06 14:07 UTC
OS: Arch Linux
Window manager: awesomewm
Fyrox version: 0.29

CPU: Intel i5-9300H (8) @ 2.400GHz
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q

I am trying to work through the 2D platformer tutorial (https://fyrox-book.github.io/fyrox/tutorials/platformer/part1.html).

The editor is very slow and unresponsive; I've attached a video. Sometimes, it is a little bit better (just kinda slow, not unbearable) for like a minute but it then it goes back to being unusable. I think maybe the drop down menus might be what trigger it. It seems like every time I open a drop down menu, the editor just freezes.

I didn't record the video with sound, but I am hovering my mouse over the nodes (even without clicking, this should highlight them with a dark colour), then also clicking on them, and the clicks aren't registered until like 10 seconds later. As you can see, when I open the "Create child" menu, everything just freezes and it becomes completely unresponsive.

https://user-images.githubusercontent.com/31142852/223132033-f525de4b-357c-4af7-b633-13fda7ce4b7a.mp4

**Comment by mrDIMAS** [comment] 2023-03-07 19:06
Stupid question, but I have to ask - did you run the editor in Release mode? Besides that, the overall slowdown of context menus is a known bug, but I can't reproduce it stable enough to start searching for a potential fix.

**Comment by christofferaakre** [comment] 2023-03-07 19:13
I ran it with `cargo run --package editor --release` as explained in the tutorial, so I think this runs the editor in release mode, right? And also, fair enough, if you can't reproduce it, I suppose it is almost impossible to troubleshoot it. No worries :)

**Comment by IceGuye** [comment] 2023-03-09 04:58
Do you run the editor by using your NVIDIA GeForce GTX 1650? 
It could be like:
`DRI_PRIME=1 cargo run --package editor --release`

**Comment by mrDIMAS** [comment] 2023-03-11 09:08
@christofferaakre I was able to reproduce the bug using steps found by @IceGuye and it should be fixed now. Could you please confirm that there's no performance degradation?

**Comment by christofferaakre** [comment] 2023-03-11 11:42
@mrDIMAS I'm out right now but will test when I get home. Thanks!

**Comment by christofferaakre** [comment] 2023-03-11 14:44
@mrDIMAS Yes, it is super smooth now. Thanks for fixing it so quiklcy!!
Also, I didn't have to do anything? No update or anything? I don't quite understand how whatever fix you found was applied to my version of the editor, but somehow it was?

**Comment by mrDIMAS** [comment] 2023-03-11 14:47
Right, I should mention that you should update first, since you're using stable 0.29. Please use [this instruction](https://fyrox-book.github.io/fyrox/beginning/scripting.html#using-latest-engine-version) to update to the latest engine version.

**Comment by christofferaakre** [comment] 2023-03-11 14:49
It's very weird that it all of a sudden is very smooth then, hmm.. Thanks for the link though!

**Comment by mrDIMAS** [comment] 2023-03-11 15:03
Here's the steps-to-reproduce: create two scene nodes and select one after another for a minute or so (a bit easier than @IceGuye 's). If the bug is still there, you'll get serious performance degradation.

**Closed** 2023-03-15 18:01 UTC
